### ISSUE TITLE
Add to awesome-dbos

### ISSUE THREAD

**Issue by kraftp** [demetris-manikas/dbos-docker-boilerplate#5]
We're making a repository called [awesome-dbos](https://github.com/dbos-inc/awesome-dbos) to collect all DBOS articles, resources, and community contributions. Can we add this repository to the list?  Thanks!

**Comment by demetris-manikas** [comment]
Happy to hear you consider this valuable.
I will say yes even though this might turn this repo from a toy project to a repo with "issues" :).

**Comment by kraftp** [comment]
Thanks--we really appreciate your contributions to DBOS!
